---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jas
spec:
  template:
    spec:
      containers:
      - image: gcr.io/forgerock-autoid/ci/sovongsa/github-push-job/jas:492342242
        name: jas
