---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jasnode
spec:
  template:
    spec:
      containers:
      - image: gcr.io/forgerock-autoid/ci/jnw/a-2468/jas:367627491
        name: jasnode
