apiVersion: v1
kind: ConfigMap
metadata:
    name: iga-nginx-platform-confd
    labels:
        app: autoid-nginx
        product: autoid
data:
    default.conf: |
        map $sent_http_content_type $expires {
        default                    off;
        text/html                  max;
        text/css                   max;
        application/javascript     max;
        application/json           epoch;
        ~image/                    max;
        }
        server {
        listen       18081;
        server_name  localhost;
        http2_max_field_size 512k;
        http2_max_header_size 512k;
        client_body_buffer_size     512k;
        client_header_buffer_size   512k;
        large_client_header_buffers 8 512k;
        location / {
            add_header Cache-Control no-store;
                add_header Pragma no-cache;
            root   /usr/share/nginx/html;
            try_files $uri /index.html;
        }
        location ~ ^/iga/ {
            set_secure_random_alphanum $cspNonce 32;
            sub_filter_once off;
            sub_filter_types *;
            sub_filter **CSP_NONCE** $cspNonce;
            add_header Content-Security-Policy "script-src 'self' 'nonce-$cspNonce'";
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header Referrer-Policy "no-referrer-when-downgrade";
            add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
            add_header          X-Content-Type-Options nosniff always;
            add_header          X-Frame-Options "SAMEORIGIN" always;
            add_header          X-XSS-Protection "1; mode=block" always;
            resolver kube-dns.kube-system.svc.cluster.local valid=10s;
            set $upstream http://iga-api.#NAMESPACE#.svc.cluster.local:3005;
            proxy_pass $upstream;
        }
        location ~ ^/openidm/ {
            set_secure_random_alphanum $cspNonce 32;
            sub_filter_once off;
            sub_filter_types *;
            sub_filter **CSP_NONCE** $cspNonce;
            add_header Content-Security-Policy "script-src 'self' 'nonce-$cspNonce'";
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header Referrer-Policy "no-referrer-when-downgrade";
            add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
            add_header          X-Content-Type-Options nosniff always;
            add_header          X-Frame-Options "SAMEORIGIN" always;
            add_header          X-XSS-Protection "1; mode=block" always;
            resolver kube-dns.kube-system.svc.cluster.local valid=10s;
            set $upstream https://openidm.#NAMESPACE#.svc.cluster.local:8443;
            proxy_pass $upstream;
        }
         location ~ ^/api/ {
            set_secure_random_alphanum $cspNonce 32;
            sub_filter_once off;
            sub_filter_types *;
            sub_filter **CSP_NONCE** $cspNonce;
            add_header Content-Security-Policy "script-src 'self' 'nonce-$cspNonce'";
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header Referrer-Policy "no-referrer-when-downgrade";
            add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
            add_header          X-Content-Type-Options nosniff always;
            add_header          X-Frame-Options "SAMEORIGIN" always;
            add_header          X-XSS-Protection "1; mode=block" always;
            resolver kube-dns.kube-system.svc.cluster.local valid=10s;
            set $upstream http://zoran-api.#NAMESPACE#.svc.cluster.local:8080;
            proxy_pass $upstream;
        }
         location ~ ^/conf/ {
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header Referrer-Policy "no-referrer-when-downgrade";
            add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
            add_header          X-Content-Type-Options nosniff always;
            add_header          X-Frame-Options "SAMEORIGIN" always;
            add_header          X-XSS-Protection "1; mode=block" always;
            expires -1;
            add_header Cache-Control no-store;
            resolver kube-dns.kube-system.svc.cluster.local valid=10s;
            set $upstream http://configuration-service.#NAMESPACE#.svc.cluster.local:8080;
            rewrite ^/conf/(.*) /$1  break;
            proxy_pass $upstream$uri$is_args$args;
        }
        location ~ ^/jas/ {
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header Referrer-Policy "no-referrer-when-downgrade";
            add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
            add_header          X-Content-Type-Options nosniff always;
            add_header          X-Frame-Options "SAMEORIGIN" always;
            add_header          X-XSS-Protection "1; mode=block" always;
            expires -1;
            add_header Cache-Control no-store;
            resolver kube-dns.kube-system.svc.cluster.local valid=10s;
            set $upstream https://jas.#NAMESPACE#.svc.cluster.local:10081;
            rewrite ^/jas/(.*) /$1  break;
            proxy_pass $upstream$uri$is_args$args;
        }
            expires $expires;
        }
