---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iga-platform-ui
  labels:
    app: autoid-iga-platform-ui
    product: autoid
spec:
  selector:
    matchLabels:
      app: autoid-iga-platform-ui
      product: autoid
  template:
    metadata:
      labels:
        app: autoid-iga-platform-ui
        product: autoid
    spec:
      containers:
      - image:
        name: iga-platform-ui
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: iga-nginx-platform-confd
      imagePullSecrets:
        - name: autoid-registry
      volumes:
      - name: iga-nginx-platform-confd
        configMap:
          name: iga-nginx-platform-confd



