
apiVersion: v1
kind: Service
metadata:
  labels:
    app: autoid-iga-platform-ui
    product: autoid
  name: iga-platform-ui
spec:
  ports:
    - port: 18081
      protocol: TCP
      targetPort: 18081
      name: http
  selector:
    app: autoid-iga-platform-ui
    product: autoid
  type: ClusterIP