---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    product: autoid
spec:
  selector:
    matchLabels:
      app: nginx
      product: autoid
  template:
    metadata:
      labels:
        app: nginx
        product: autoid
    spec:
      containers:
      - image: gcr.io/forgerock-autoid/ci/develop/nginx:263174364
        name: nginx
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-conf
            subPath: nginx.conf
          - mountPath: /etc/nginx/conf.d/
            name: nginx-confd
          - mountPath: /etc/nginx/cert/
            name: nginx-certs
            readOnly: true
      imagePullSecrets:
        - name: autoid-registry
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: nginx-confd
        configMap:
          name: nginx-confd
      - name: nginx-certs
        secret:
          secretName: nginx-certs
