---
apiVersion: v1
kind: Secret
metadata:
  name: etl-env
  labels:
    app: etl
    product: autoid
type: Opaque
data:
  JAS_TLS_KEYSTORE_PASS: "QWNjIzEyMzQ="
  JAS_TLS_TRUSTSTORE_PASS: "QWNjIzEyMzQ="
  ES_KEYSTORE_PASSWORD: "QWNjIzEyMzQ="
  ES_TRUSTSTORE_PASSWORD: "QWNjIzEyMzQ="
