---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iga-ui
spec:
  template:
    spec:
      containers:
      - image: gcr.io/forgerock-autoid/ci/develop/iga-ui:442259135
        name: iga-ui
        