---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../common/openidm/base

patchesStrategicMerge:
- openidm_config_map.yaml
- openidm_deployment.yaml
- openidm_secret.yaml
- openidm_secretagent_secret.yaml
