---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../common/openidm/base

patchesStrategicMerge:
- openidm_config_map.yaml
- openidm_deployment.yaml

secretGenerator:
- name: openidm-conf-datasource
  behavior: replace
  files:
  - datasource.jdbc-default.json
- name: openidm-database
  envs:
  - openidm_database.env
