---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openidm
spec:
  template:
    spec:
      containers:
        - image: gcr.io/forgerock-autoid/ci/develop/openidm:457841415
          name: openidm
          env:
            - name: PG_OPENIDM_USER
              valueFrom:
                secretKeyRef:
                  name: openidm-database
                  key: PG_OPENIDM_USER
            - name: PG_OPENIDM_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openidm-database
                  key: PG_OPENIDM_USER_PASSWORD
            - name: PGHOST
              value: #PG_HOST# ## provisioned by user
            - name: PG_ROOT_PASSWORD
              value: #PG_ROOT_PASSWORD# ## provisioned by user
            - name: PG_OPENIDM_DATABASE
              value: openidm ## provisioned by user
            - name: OPENIDM_OPTS
              value: -Xmx4096m -Xms4096m -Dopenidm.repo.host=$(PGHOST) -Dopenidm.repo.port=5432 -Dopenidm.config.repo.enabled=true -Dopenidm.fileinstall.enabled=false -Dfelix.fileinstall.enableConfigSave=false ## provisioned by user
          volumeMounts:
            - mountPath: /var/run/secrets/idm
              name: idm-secrets
            - mountPath: /opt/openidm/conf/secrets.json
              name: secrets-json
              subPath: secrets.json
            - mountPath: /opt/openidm/conf/identityProviders.json
              name: identity-providers-json
              subPath: identityProviders.json
            - mountPath: /opt/openidm/conf/identityProvider-microsoft.json
              name: identityprovider-microsoft-json
              subPath: identityProvider-microsoft.json
            - mountPath: /opt/openidm/conf/selfservice-registration.json
              name: selfservice-registration-json
              subPath: selfservice-registration.json
            - mountPath: /opt/openidm/conf/ui-configuration.json
              name: ui-configuration-json
              subPath: ui-configuration.json
            - mountPath: /opt/openidm/bin/defaults/script/auth/populateAsManagedUserFromRelationship.js
              name: populateasmanageduserfromrelationship-js
              subPath: populateAsManagedUserFromRelationship.js
            - mountPath: /opt/openidm/conf/selfservice-socialUserClaim.json
              name: selfservice-socialuserclaim-json
              subPath: selfservice-socialUserClaim.json
            - mountPath: /opt/openidm/conf/datasource.jdbc-default.json
              name: openidm-conf-datasource
              subPath: datasource.jdbc-default.json
      volumes:
        - name: secrets-json
          configMap:
            defaultMode: 420
            name: openidm-secrets-json
        - name: identity-providers-json
          configMap:
            defaultMode: 420
            name: openidm-identity-providers-json
        - name: identityprovider-microsoft-json
          configMap:
            defaultMode: 420
            name: openidm-identityprovider-microsoft-json
        - name: selfservice-registration-json
          configMap:
            defaultMode: 420
            name: openidm-selfservice-registration-json
        - name: ui-configuration-json
          configMap:
            defaultMode: 420
            name: openidm-ui-configuration-json
        - name: selfservice-socialuserclaim-json
          configMap:
            defaultMode: 420
            name: openidm-selfservice-socialuserclaim-json
        - name: populateasmanageduserfromrelationship-js
          configMap:
            defaultMode: 420
            name: openidm-populateasmanageduserfromrelationship-js
        - name: idm-secrets
          secret:
            defaultMode: 420
            secretName: openidm
        - name: openidm-conf-datasource
          secret:
            secretName: openidm-conf-datasource
            items:
              - key: datasource.jdbc-default.json
                path: datasource.jdbc-default.json
