---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openidm
spec:
  template:
    spec:
      containers:
        - image: gcr.io/forgerock-autoid/ci/develop/openidm:492862017
          name: openidm
          env:
            - name: PG_OPENIDM_USER
              valueFrom:
                secretKeyRef:
                  name: openidm-database
                  key: PG_OPENIDM_USER
            - name: PG_OPENIDM_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openidm-database
                  key: PG_OPENIDM_USER_PASSWORD
            - name: PGHOST
              value: #PG_HOST# ## provisioned by user
            - name: PG_ROOT_PASSWORD
              value: #PG_ROOT_PASSWORD# ## provisioned by user
            - name: PG_OPENIDM_DATABASE
              value: openidm ## provisioned by user
            - name: OPENIDM_OPTS
              value: -Xmx4096m -Xms4096m -Dopenidm.repo.host=$(PGHOST) -Dopenidm.repo.port=5432 -Dopenidm.config.repo.enabled=true -Dopenidm.fileinstall.enabled=false -Dfelix.fileinstall.enableConfigSave=false ## provisioned by user
          volumeMounts:
            - mountPath: /var/run/secrets/idm
              name: idm-secrets
            - mountPath: /opt/openidm/conf/secrets.json
              name: secrets-json
              subPath: secrets.json
            - mountPath: /opt/openidm/conf/datasource.jdbc-default.json
              name: openidm-conf-datasource
              subPath: datasource.jdbc-default.json
            - name: authentication-json
              mountPath: /opt/openidm/conf/authentication.json
              subPath: authentication.json
            - name: idm-populateasmanageduser-js
              mountPath: /opt/openidm/bin/defaults/script/auth/populateAsManagedUser.js
              subPath: populateAsManagedUser.js
      volumes:
        - name: secrets-json
          configMap:
            defaultMode: 420
            name: openidm-secrets-json
        - name: idm-secrets
          secret:
            defaultMode: 420
            secretName: openidm
        - name: openidm-conf-datasource
          secret:
            secretName: openidm-conf-datasource
            items:
              - key: datasource.jdbc-default.json
                path: datasource.jdbc-default.json
        - name: authentication-json
          configMap:
            defaultMode: 420
            name: idm-authentication
        - name: idm-populateasmanageduser-js
          configMap:
            defaultMode: 420
            name: openidm-populateasmanageduser-js
