---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openidm
spec:
  template:
    spec:
      containers:
        - image: gcr.io/forgerock-autoid/ci/develop/openidm:374794351
          name: openidm
          env:
          - name: PG_OPENIDM_USER
            value: #PG_OPENIDM_USER# ## provisioned by user
          - name: PG_OPENIDM_USER_PASSWORD
            value: #PG_OPENIDM_USER_PASSWORD# ## provisioned by user
          - name: PGHOST
            value: #PG_HOST# ## provisioned by user
          - name: PG_ROOT_PASSWORD
            value: #PG_ROOT_PASSWORD# ## provisioned by user
          - name: PG_OPENIDM_DATABASE
            value: openidm ## provisioned by user
          - name: OPENIDM_OPTS
            value: -Xmx1024m -Xms1024m -Dopenidm.repo.host=$(PGHOST) -Dopenidm.repo.port=5432 ## provisioned by user
          volumeMounts:
          - mountPath: /var/run/secrets/idm
            name: idm-secrets
          - mountPath: /opt/openidm/conf/secrets.json
            name: secrets-json
            subPath: secrets.json
      volumes:
      - name: secrets-json
        configMap:
          defaultMode: 420
          name: openidm-secrets-json
      - name: idm-secrets
        secret:
          defaultMode: 420
          secretName: openidm

