---
apiVersion: v1
kind: Secret
metadata:
  name: etl-env
  labels:
    app: etl
    product: autoid
type: Opaque
data:
  JAS_TLS_KEYSTORE_PASS: "#TLS_STORE_PASS#"
  JAS_TLS_TRUSTSTORE_PASS: "#TLS_STORE_PASS#"
  ES_USERNAME: "#ES_USERNAME#"  ## provisioned by user
  ES_PASSWORD: "#ES_PASSWORD#"  ## provisioned by user
  ES_KEYSTORE_PASSWORD: "#TLS_STORE_PASS#"
  ES_TRUSTSTORE_PASSWORD: "#TLS_STORE_PASS#"
