---
apiVersion: v1
kind: Secret
metadata:
  name: etl-env
  labels:
    app: etl
    product: autoid
type: Opaque
data:
  JAS_TLS_KEYSTORE_PASS: ""
  JAS_TLS_TRUSTSTORE_PASS: ""
  ES_KEYSTORE_PASSWORD: ""
  ES_TRUSTSTORE_PASSWORD: ""
