---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: autoid-iga-ui
    product: autoid
  name: iga-ui
spec:
  ports:
    - port: 18080
      protocol: TCP
      targetPort: 18080
      name: http
  selector:
    app: autoid-iga-ui
    product: autoid
  type: ClusterIP
