---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: forgerock-iga-api
    product: autoid
  name: iga-api
spec:
  ports:
    - port: 3005
      protocol: TCP
      targetPort: 3005
      name: http
  selector:
    app: forgerock-iga-api
    product: autoid
  type: ClusterIP
