---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../common/jas/base
- ../../common/etl/base
- ../../common/openidm/base
- ../../common/nginx/base
- ../../common/prometheus-metrics/base
- iga-api/base
- iga-ui/base
- iga-platform-ui/base

patchesStrategicMerge:
- iga-api/overlays/iga_api_config_map.yaml
- iga-api/overlays/iga_api_deployment.yaml
- iga-api/overlays/iga_api_secret.yaml
- iga-ui/overlays/iga_ui_deployment.yaml
- iga-platform-ui/overlays/deployment.yaml
- jas/overlays/jas_config_map.yaml
- jas/overlays/jas_deployment.yaml
- jas/overlays/jas_secret.yaml
- etl/overlays/etl_config_map.yaml
- etl/overlays/etl_secret.yaml
- nginx/overlays/nginx_service.yaml
- nginx/overlays/nginx_config_map.yaml
- openidm/overlays/openidm_config_map.yaml
- openidm/overlays/openidm_statefulset.yaml
- prometheus-metrics/overlays/prometheus-metrics_deployment.yaml
- prometheus-metrics/overlays/prometheus-metrics_config_map.yaml

secretGenerator:
  - name: openidm-conf-datasource
    files:
      - openidm/overlays/datasource.jdbc-default.json

  - name: openidm-database
    envs:
      - openidm/overlays/openidm_database.env
