---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iga-api
  labels:
    app: forgerock-iga-api
    product: autoid
spec:
  selector:
    matchLabels:
      app: forgerock-iga-api
      product: autoid
  template:
    metadata:
      labels:
        app: forgerock-iga-api
        product: autoid
    spec:
      containers:
      - image: containerImage
        name: iga-api      
        envFrom:
        - configMapRef:
            name: iga-api-cm
        - secretRef:
            name: iga-api-secret
        volumeMounts:
          - mountPath: /jas-tls/
            name: iga-api-jas-certs
      imagePullSecrets:
        - name: autodid-registry
      volumes:
      - name: iga-api-jas-certs
        secret:
          secretName: iga-api-jas-certs
