---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-conf-datasource
data:
  datasource.jdbc-default.json: |
    {
        "driverClass" : "org.postgresql.Driver",
        "jdbcUrl" : "jdbc:postgresql://&{openidm.repo.host}:&{openidm.repo.port}/openidm",
        "databaseName" : "openidm",
        "username" : "#PG_OPENIDM_USER#",
        "password" : "#PG_OPENIDM_USER_PASSWORD#",
        "connectionTimeout" : 30000,
        "connectionPool" : {
            "type" : "hikari",
            "minimumIdle" : 20,
            "maximumPoolSize" : 50
        }
    }

---
kind: ConfigMap
metadata:
  name: idm-conf-audit
apiVersion: v1
data:
  audit.json: |
    {
        "auditServiceConfig" : {
            "handlerForQueries" : "json",
            "availableAuditEventHandlers" : [
                "org.forgerock.audit.handlers.csv.CsvAuditEventHandler",
                "org.forgerock.audit.handlers.elasticsearch.ElasticsearchAuditEventHandler",
                "org.forgerock.audit.handlers.jms.JmsAuditEventHandler",
                "org.forgerock.audit.handlers.json.JsonAuditEventHandler",
                "org.forgerock.audit.handlers.json.stdout.JsonStdoutAuditEventHandler",
                "org.forgerock.openidm.audit.impl.RepositoryAuditEventHandler",
                "org.forgerock.openidm.audit.impl.RouterAuditEventHandler",
                "org.forgerock.audit.handlers.splunk.SplunkAuditEventHandler",
                "org.forgerock.audit.handlers.syslog.SyslogAuditEventHandler",
                "org.forgerock.audit.handlers.jas.JasAuditEventHandler"
            ],
            "filterPolicies" : {
                "field" : {
                    "excludeIf" : [ ],
                    "includeIf" : [
                            "/config/before",
                            "/config/after",
                            "/activity/before",
                            "/activity/after"
                    ]
                }
            },
            "caseInsensitiveFields" : [
                "/access/http/request/headers",
                "/access/http/response/headers"
            ]
        },
        "eventHandlers" : [
        {
                "class" : "org.forgerock.audit.handlers.jas.JasAuditEventHandler",
                "config" : {
                    "name" : "jas",
                    "tenantId" : "#JAS_TENANT_ID#",
                    "jasUrl" : "https://jasnode:10081",
                    "nameSpace" : "openidm",
                    "parserClass" : "org.forgerock.audit.handlers.jas.OpenIdmEventParser",
                    "topicMetaFields" : {
                            "activity": ["transactionId", "userId", "trackingId", "runAs", "operation", "changedFields", "message", "eventName", "status", "passwordChanged", "context"],
                            "config": ["transactionId", "userId", "trackingId", "runAs", "operation", "changedFields"]
                    },
                    "topics" : [
                            "activity",
                            "config"
                    ],
                    "disableSslCertificateVerification": true,
                    "enabled": true
                }
            },
            {
                "class" : "org.forgerock.audit.handlers.json.JsonAuditEventHandler",
                "config" : {
                    "name" : "json",
                    "logDirectory" : "&{idm.data.dir}/audit",
                    "buffering" : {
                        "maxSize" : 100000,
                        "writeInterval" : "100 millis"
                    },
                    "topics" : [
                        "access",
                        "activity",
                        "sync",
                        "authentication",
                        "config"
                    ]
                }
            },
            {
                "class" : "org.forgerock.audit.handlers.json.stdout.JsonStdoutAuditEventHandler",
                "config" : {
                    "name" : "json-stdout",
                    "topics" : [
                        "activity",
                        "sync",
                        "authentication",
                        "config"
                    ]
                }
            },
            {
                "class": "org.forgerock.openidm.audit.impl.RepositoryAuditEventHandler",
                "config": {
                    "name": "repo",
                    "enabled": false,
                    "topics": [
                        "access",
                        "activity",
                        "sync",
                        "authentication",
                        "config"
                    ]
                }
            }
        ],
        "eventTopics" : {
            "config" : {
                "filter" : {
                    "actions" : [
                        "create",
                        "update",
                        "delete",
                        "patch",
                        "action"
                    ]
                }
            },
            "activity" : {
                "filter" : {
                    "actions" : [
                        "create",
                        "update",
                        "delete",
                        "patch",
                        "action"
                    ]
                },
                "watchedFields" : [ ],
                "passwordFields" : [
                    "password"
                ]
            }
        },
        "exceptionFormatter" : {
            "type" : "text/javascript",
            "file" : "bin/defaults/script/audit/stacktraceFormatter.js"
        }
    }

---
kind: ConfigMap
metadata:
  name: idm-conf-metrics
apiVersion: v1
data:
  metrics.json: |
    {
        "enabled" : true
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-secrets-json
data:
  secrets.json: |
    {
    "stores": [
    {
      "name": "mainKeyStore",
      "class": "org.forgerock.openidm.secrets.config.FileBasedStore",
      "config": {
        "file": "&{openidm.keystore.location|/var/run/secrets/idm/keystore.jceks}",
        "storetype": "&{openidm.keystore.type|JCEKS}",
        "providerName": "&{openidm.keystore.provider|SunJCE}",
        "storePassword": "&{openidm.keystore.password|changeit}",
        "mappings": [
          {
            "secretId" : "idm.default",
            "types": [ "ENCRYPT", "DECRYPT" ],
            "aliases": [ "&{openidm.config.crypto.alias|openidm-sym-default}" ]
          },
          {
            "secretId" : "idm.config.encryption",
            "types": [ "ENCRYPT", "DECRYPT" ],
            "aliases": [ "&{openidm.config.crypto.alias|openidm-sym-default}" ]
          },
          {
            "secretId" : "idm.password.encryption",
            "types": [ "ENCRYPT", "DECRYPT" ],
            "aliases": [ "&{openidm.config.crypto.alias|openidm-sym-default}" ]
          },
          {
            "secretId" : "idm.jwt.session.module.encryption",
            "types": [ "ENCRYPT", "DECRYPT" ],
            "aliases": [ "&{openidm.https.keystore.cert.alias|openidm-localhost}" ]
          },
          {
            "secretId" : "idm.jwt.session.module.signing",
            "types": [ "SIGN", "VERIFY" ],
            "aliases": [ "&{openidm.config.crypto.jwtsession.hmackey.alias|openidm-jwtsessionhmac-key}" ]
          },
          {
            "secretId" : "idm.selfservice.encryption",
            "types": [ "ENCRYPT", "DECRYPT" ],
            "aliases": [ "selfservice" ]
          },
          {
            "secretId" : "idm.selfservice.signing",
            "types": [ "SIGN", "VERIFY" ],
            "aliases": [ "&{openidm.config.crypto.selfservice.sharedkey.alias|openidm-selfservice-key}" ]
          }
        ]
      }
    },
    {
      "name": "mainTrustStore",
      "class": "org.forgerock.openidm.secrets.config.FileBasedStore",
      "config": {
        "file": "&{openidm.truststore.location|/var/run/secrets/idm/truststore}",
        "storetype": "&{openidm.truststore.type|JKS}",
        "providerName": "&{openidm.truststore.provider|SUN}",
        "storePassword": "&{openidm.truststore.password|changeit}",
        "mappings": [
        ]
      }
    }
    ],
    "populateDefaults": true
    }
