---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iga-api
spec:
  selector:
    matchLabels:
      app: forgerock-iga-api
      product: autoid
  template:
    metadata:
      labels:
        app: forgerock-iga-api
        product: autoid
    spec:
      containers:
      - image: gcr.io/forgerock-autoid/ci/develop/iga-api:458804942
        name: iga-api      
        