---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    product: autoid
  name: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
    - port: 443
      protocol: TCP
      targetPort: 443
      name: https
  selector:
    app: nginx
    product: autoid
  type: LoadBalancer
  loadBalancerIP: "" ## provisioned by user