---
apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-confd
    labels:
        app: nginx
        product: autoid
data:
    jas.conf: |
        server {
            listen 80;
            server_name ~^jas.#DOMAIN_NAME#\.*;

            return 301 https://$host$request_uri;

        }

        server {
            listen 443 http2 ssl;
            listen [::]:443 http2 ssl;

            server_name ~^jas.#DOMAIN_NAME#\.*;

            access_log  logs/jas-access.log;

            proxy_set_header host $host;

            proxy_connect_timeout       60000;
            proxy_send_timeout          60000;
            proxy_read_timeout          60000;
            send_timeout                60000;

            #Max acceptable input payload
            client_max_body_size 100m;

            location /{
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
                add_header Referrer-Policy "no-referrer-when-downgrade";
                add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";

                add_header          X-Content-Type-Options nosniff always;
                add_header          X-Frame-Options "SAMEORIGIN" always;
                add_header          X-XSS-Protection "1; mode=block" always;

                proxy_pass https://jas:10081;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                real_ip_recursive on;
                #Block all http methods except GET and POST. HEAD is implcicit - its a just special case of GET
                limit_except GET POST PUT PATCH DELETE {
                    deny  all;
                }
            }
        }
    iga-ui.conf: |
        server {
            listen 80;
            server_name ~^#IGA_UI_SUBDOMAIN#.#DOMAIN_NAME#\.*;
            return 301 https://$host$request_uri;
        }
        server {
            listen 443 http2 ssl;
            listen [::]:443 http2 ssl;
            server_name ~^#IGA_UI_SUBDOMAIN#.#DOMAIN_NAME#\.*;
            access_log  logs/iga-ui-access.log;
            proxy_set_header host $host;
            proxy_connect_timeout       60000;
            proxy_send_timeout          60000;
            proxy_read_timeout          60000;
            send_timeout                60000;
            location /{
            set_secure_random_alphanum $cspNonce 32;
            sub_filter_once off;
            sub_filter_types *;
            sub_filter **CSP_NONCE** $cspNonce;
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header Referrer-Policy "no-referrer-when-downgrade";
            add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
            add_header          X-Content-Type-Options nosniff always;
            add_header          X-Frame-Options "SAMEORIGIN" always;
            add_header          X-XSS-Protection "1; mode=block" always;
            proxy_pass http://iga-ui:18080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_cookie_path ~^(.+)$ "$1; domain=#DOMAIN_NAME#";
            real_ip_recursive on;
            limit_except GET POST PATCH DELETE PUT {
                deny  all;
            }
          }
        }
    iga-platform-ui.conf: |
        server {
            listen 80;
            server_name ~^#PLATFORM_UI_SUBDOMAIN#.#DOMAIN_NAME#\.*;
            return 301 https://$host$request_uri;
        }
        server {
            listen 443 http2 ssl;
            listen [::]:443 http2 ssl;
            server_name ~^#PLATFORM_UI_SUBDOMAIN#.#DOMAIN_NAME#\.*;
            access_log  logs/iga-ui-access.log;
            proxy_set_header host $host;
            proxy_connect_timeout       60000;
            proxy_send_timeout          60000;
            proxy_read_timeout          60000;
            send_timeout                60000;
            http2_max_field_size 512k;
            http2_max_header_size 512k;
            client_body_buffer_size     512k;
            client_header_buffer_size   512k;
            large_client_header_buffers 8 512k;
            location /{
            set_secure_random_alphanum $cspNonce 32;
            sub_filter_once off;
            sub_filter_types *;
            sub_filter **CSP_NONCE** $cspNonce;
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            add_header Referrer-Policy "no-referrer-when-downgrade";
            add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
            add_header          X-Content-Type-Options nosniff always;
            add_header          X-Frame-Options "SAMEORIGIN" always;
            add_header          X-XSS-Protection "1; mode=block" always;
            proxy_pass http://iga-platform-ui:18081;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_cookie_path ~^(.+)$ "$1; domain=#DOMAIN_NAME#";
            real_ip_recursive on;
            limit_except GET POST PATCH DELETE PUT {
                deny  all;
            }
          }
        }
    iga-api.conf: |
        server {
            listen 80;
            server_name ~^iga-api.#DOMAIN_NAME#\.*;
            return 301 https://$host$request_uri;
        }
        server {
            listen 443 http2 ssl;
            listen [::]:443 http2 ssl;
            server_name ~^iga-api.#DOMAIN_NAME#\.*;
            access_log  logs/iga-api-access.log;
            proxy_set_header host $host;
            proxy_connect_timeout       60000;
            proxy_send_timeout          60000;
            proxy_read_timeout          60000;
            send_timeout                60000;
            location /{
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
                add_header Referrer-Policy "no-referrer-when-downgrade";
                add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
                add_header          X-Content-Type-Options nosniff always;
                add_header          X-Frame-Options "SAMEORIGIN" always;
                add_header          X-XSS-Protection "1; mode=block" always;
                proxy_pass http://iga-api:3005;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                real_ip_recursive on;
                limit_except GET POST PATCH DELETE PUT {
                    deny  all;
                }
            }
        }
    iga-openidm.conf: |
        server {
            listen 80;
            server_name ~^idm.#DOMAIN_NAME#\.*;
            return 301 https://$host$request_uri;
        }
        server {
            listen 443 http2 ssl;
            listen [::]:443 http2 ssl;
            server_name ~^idm.#DOMAIN_NAME#\.*;
            access_log  logs/idm-access.log;
            proxy_set_header host $host;
            proxy_connect_timeout       60000;
            proxy_send_timeout          60000;
            proxy_read_timeout          60000;
            send_timeout                60000;
            http2_max_field_size 512k;
            http2_max_header_size 512k;
            client_body_buffer_size     512k;
            client_header_buffer_size   512k;
            large_client_header_buffers 8 512k;
            location /{
                set_secure_random_alphanum $cspNonce 32;
                sub_filter_once off;
                sub_filter_types *;
                sub_filter **CSP_NONCE** $cspNonce;
                add_header Content-Security-Policy "unsafe-inline";
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
                add_header Referrer-Policy "no-referrer-when-downgrade";
                add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
                add_header          X-Content-Type-Options nosniff always;
                add_header          X-Frame-Options "SAMEORIGIN" always;
                add_header          X-XSS-Protection "1; mode=block" always;
                proxy_pass http://openidm:8080;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_cookie_path ~^(.+)$ "$1; domain=#DOMAIN_NAME#";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                real_ip_recursive on;
                limit_except GET POST PUT PATCH DELETE {
                    deny  all;
                }
            }
        }

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
    labels:
        app: nginx
        product: autoid
data:
    nginx.conf: |
        load_module modules/ndk_http_module.so;
        load_module modules/ngx_http_set_misc_module.so;

        user  nginx;
        worker_processes  1;

        error_log  logs/error.log warn;
        pid        /var/run/nginx.pid;


        events {
            worker_connections  1024;
        }


        http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;

            log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

            access_log  logs/access.log  main;

            sendfile        on;
            #tcp_nopush     on;

            keepalive_timeout  65;

            #gzip  on;

            add_header          X-Content-Type-Options nosniff always;
            add_header          X-Frame-Options "SAMEORIGIN" always;
            add_header          X-XSS-Protection "1; mode=block" always;

            #SSL Settings
            ssl_certificate     /etc/nginx/cert/fullchain.pem;
            ssl_certificate_key /etc/nginx/cert/privkey.pem;
            ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-CHACHA20-POLY1305;
            ssl_ecdh_curve      secp384r1;
            ssl_protocols       TLSv1.2;
            ssl_prefer_server_ciphers on; 
            ssl_session_cache shared:SSL:10m;
            ssl_session_timeout 10m;
            ssl_session_tickets off;
            server_tokens       off;
            server_name_in_redirect off;
            
            #OCSP Stapling
            ssl_stapling on;
            ssl_stapling_verify on;

            #HTTP Strict Transport Security (HSTS)
            #Enable below line if the certificate is not self signed (MUST)
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

            include /etc/nginx/conf.d/*.conf;
        }
