---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iga-platform-ui
spec:
  template:
    spec:
      containers:
      - image: gcr.io/forgerock-autoid/ci/jnw/2468/iga-platform-ui:372800512
        name: iga-platform-ui
        