---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iga-platform-ui
spec:
  template:
    spec:
      containers:
      - image: gcr.io/forgerock-autoid/ci/sovongsa/github-push-job/iga-platform-ui:492342242
        name: iga-platform-ui
        