---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iga-platform-ui
spec:
  template:
    spec:
      containers:
      - image: gcr.io/forgerock-autoid/ci/develop/iga-platform-ui:478191540
        name: iga-platform-ui
        