---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jasnode
    product: autoid
  name: jasnode
spec:
  ports:
    - port: 10081
      protocol: TCP
      targetPort: 10081
      name: http
  selector:
    app: jasnode
    product: autoid
  type: ClusterIP
