---
apiVersion: batch/v1
kind: Job
metadata:
  name: iga-datastore-schema-job
spec:
  template:
    spec:
      containers:
        - name: iga-datastore-schema-job
          image: gcr.io/forgerock-autoid/ci/jnw/a-2468/tenancy-initializer:369346259
          env:
            - name: TENANT_NAME
              value: <ADD HERE> # example: jul-30-test
      imagePullSecrets:
        - name: autoid-registry
      restartPolicy: Never
      serviceAccount: iga-workload-identity
  backoffLimit: 1


