---
apiVersion: batch/v1
kind: Job
metadata:
  name: iga-schema-seed-job
spec:
  template:
    spec:
      containers:
      - name: iga-schema-seed-job
        image: gcr.io/forgerock-autoid/ci/jnw/a-2468/iga-demo-data:367644297
        command: ["bash","-c","/opt/iga-seed-data/script/conf/confLoader.py"]
        env:
          - name: OPENIDM_ADMIN_PASSWORD
            value: #OPENIDM_ADMIN_PASSWORD# ## pro
      restartPolicy: Never
      imagePullSecrets:
        - name: autoid-registry
  backoffLimit: 1
