---
apiVersion: batch/v1
kind: Job
metadata:
  name: iga_readonly_ldap_seed_job
spec:
  template:
    spec:
      containers:
      - name: iga_readonly_ldap_seed_job
        image: gcr.io/forgerock-autoid/ci/develop/iga-demo-data:429451609
        command: ["bash","-c","/opt/iga-seed-data/script/conf/ldapAppOnboarding.py"]
      restartPolicy: Never
      imagePullSecrets:
        - name: autodid-registry
  backoffLimit: 1
