---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-secrets
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - create
      - update
      - get
      - list
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-secrets-to-sa
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: modify-secrets
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: iga-create-secrets-job
spec:
  template:
    spec:
      containers:
        - name: iga-create-secrets-job
          image: gcr.io/forgerock-autoid/ci/jnw/a-2468/iga-secrets-job:368890182
          workingDir: /app
      imagePullSecrets:
        - name: autodid-registry
      restartPolicy: Never
      serviceAccount: internal-kubectl
  backoffLimit: 1
