---
resources:
- openidm_config_map.yaml
- openidm_statefulset.yaml
- openidm_service.yaml
- openidm_secret.yaml

configMapGenerator:

  - name: workflow-json
    files:
      - workflow.json

  - name: endpoint-iga-api-json
    files:
      - endpoint-iga-api.json

  - name: idm-iga-api-handler-js
    files:
      - idm-iga-api-handler.js

  - name: iga-basic-revocation-bpmn20-xml
    files:
      -  iga-basic-revocation.bpmn20.xml

  - name: schedule-handler
    files:
      - scheduleHandler.js
