---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: autoid-openidm
    product: autoid
  name: openidm
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: https
  selector:
    app: autoid-openidm
    product: autoid
  type: ClusterIP
                  