---
kind: ConfigMap
metadata:
  name: idm-conf-repo
apiVersion: v1
data:
  repo.init.json: |
    {
      "insert" : {
        "internal/role" : [
          {
            "id" : "openidm-admin",
            "name" : "openidm-admin",
            "description" : "Administrative access"
          },
          {
            "id" : "openidm-authorized",
            "name" : "openidm-authorized",
            "description" : "Basic minimum user"
          },
          {
            "id" : "openidm-reg",
            "name" : "openidm-reg",
            "description" : "Anonymous access"
          },
          {
            "id" : "openidm-cert",
            "name" : "openidm-cert",
            "description" : "Authenticated via certificate"
          },
          {
            "id" : "openidm-tasks-manager",
            "name" : "openidm-tasks-manager",
            "description" : "Allowed to reassign workflow tasks"
          },
          {
            "id" : "platform-provisioning",
            "name" : "platform-provisioning",
            "description" : "Platform provisioning access"
          },
     {
        "id": "governance-administrator",
        "name": "governance-administrator",
        "description": "Manage governance operations"
       },
       {
        "id": "access-request-admin",
        "name": "access-request-admin",
        "description": "Administrative access to Access Request application"
       },
       {
        "id": "glossary-admin",
        "name": "glossary-admin",
        "description": "Administrative access to the glossary"
       }
        ],
        "internal/user" : [
          {
            "id" : "openidm-admin",
            "password" : "&{openidm.admin.password}"
          },
          {
            "id" : "anonymous",
            "password" : "anonymous"
          },
          {
            "id" : "idm-provisioning"
          }
        ]
      }
    }

---
kind: ConfigMap
metadata:
  name: idm-conf-audit
apiVersion: v1
data:
  audit.json: ""

---
kind: ConfigMap
metadata:
  name: idm-conf-metrics
apiVersion: v1
data:
  metrics.json: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-secrets-json
data:
  secrets.json: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-identity-providers-json
data:
  identityProviders.json: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-identityprovider-microsoft-json
data:
  identityProvider-microsoft.json: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-selfservice-registration-json
data:
  selfservice-registration.json: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-ui-configuration-json
data:
  ui-configuration.json: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-selfservice-socialuserclaim-json
data:
  selfservice-socialUserClaim.json: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openidm-populateasmanageduserfromrelationship-js
data:
  populateAsManagedUserFromRelationship.js: ""
