---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openidm
  labels:
    app: autoid-openidm
    product: autoid
spec:
  selector:
    matchLabels:
      app: autoid-openidm
      product: autoid
  template:
    metadata:
      labels:
        app: autoid-openidm
        product: autoid
    spec:
      containers:
        - image: ""
          name: openidm
          env:
          - name: PG_OPENIDM_USER_PASSWORD
            value: 
          - name: PG_OPENIDM_USER
            value: 
          - name: PGHOST
            value: 
          - name: PG_ROOT_PASSWORD
            value: 
          - name: PG_OPENIDM_DATABASE
            value: 
          - name: OPENIDM_OPTS
            value:
          volumeMounts:
            - mountPath: /opt/openidm/script/idm-iga-api-handler.js
              name: idm-iga-api-handler-js
              subPath: idm-iga-api-handler.js
            - mountPath: /opt/openidm/workflow/iga-basic-revocation.bpmn20.xml
              name: iga-basic-revocation-bpmn20-xml
              subPath: iga-basic-revocation.bpmn20.xml
            - mountPath: /opt/openidm/conf/endpoint-iga-api.json
              name: endpoint-iga-api-json
              subPath: endpoint-iga-api.json
            - mountPath: /opt/openidm/conf/workflow.json
              name: workflow-json
              subPath: workflow.json
            - mountPath: /opt/openidm/conf/audit.json
              name: idm-conf-audit
              subPath: audit.json
            - mountPath: /opt/openidm/conf/metrics.json
              name: idm-conf-metrics
              subPath: metrics.json
            - mountPath: /opt/openidm/resolver/
              name: idm-resolver-boot-properties
            - mountPath: /opt/openidm/conf/repo.init.json
              name: idm-conf-repo
              subPath: repo.init.json
            - mountPath: /opt/openidm/conf
              name: openidm-conf-datasource
            - mountPath: /opt/openidm/script/scheduleHandler.js
              name: schedule-handler
              subPath: scheduleHandler.js
            - name: conf-folder
              mountPath: /opt/openidm/conf
            - name: openidm-conf-datasource
              mountPath: /opt/openidm/conf/datasource.jdbc-default.json
              subPath: datasource.jdbc-default.json  
      imagePullSecrets:
        - name: autoid-registry
      volumes:
        - name: idm-conf-audit
          configMap:
            name: idm-conf-audit
        - name: idm-conf-repo
          configMap:
            name: idm-conf-repo
        - name: openidm-conf-datasource
          secret:
            secretName: openidm-conf-datasource
            items:
              - key: datasource.jdbc-default.json
                path: datasource.jdbc-default.json
        - name: idm-resolver-boot-properties
          secret:
            secretName: idm-resolver-boot-properties
        - name: idm-conf-metrics
          configMap:
            name: idm-conf-metrics
        - name: schedule-handler
          configMap:
            name: schedule-handler
        - name: workflow-json
          configMap:
            name: workflow-json
        - name: endpoint-iga-api-json
          configMap:
            name: endpoint-iga-api-json
        - name: idm-iga-api-handler-js
          configMap:
            name: idm-iga-api-handler-js
        - name: iga-basic-revocation-bpmn20-xml
          configMap:
            name: iga-basic-revocation-bpmn20-xml
        - name: conf-folder
          persistentVolumeClaim:
            claimName: openidm-pvc

