---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 60s
      evaluation_interval: 60s
    scrape_configs:
      - job_name: 'jas'
        scheme: https
        metrics_path: '/metrics'
        static_configs:
        - targets: ['jas.iga.svc.cluster.local:10081']
        tls_config:
          insecure_skip_verify: true
      - job_name: 'openidm'
        metrics_path: 'openidm/metrics/prometheus'
        scheme: http
        basic_auth:
          username: 'prometheus'
          password: 'prometheus'
        static_configs:
        - targets: ['openidm.iga.svc.cluster.local:8080']