---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iga-jas-role
  labels:
rules:
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iga-jas-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iga-jas-role
subjects:
- kind: ServiceAccount
  name: iga-workload-identity
  apiGroup: ""
