---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jasnode-cm
  labels:
    app: jasnode
    product: autoid
data:
  CADENCE_HOST: "cadence"
  CADENCE_PORT: "7933"
  CASSANDRA_AUTHENTICATION_ENABLED: "true"
  CASSANDRA_CONTACT_POINTS: ""
  CASSANDRA_KEYSTORE_PATH: "/cassandra-certs/zoran-cassandra-client-keystore.jks"
  CASSANDRA_PORT: "9042"
  CASSANDRA_SSL_ENABLED: "true"
  CASSANDRA_TRUSTSTORE_PATH: "/cassandra-certs/zoran-cassandra-server-truststore.jks"
  CLOUD_DATASTORE_ENABLED: "true"
  CLOUD_DATASTORE_KEY: ""
  CLOUD_DATASTORE_PROJECT_ID: ""
  CONSUL_AUTHENTICATION_ENABLED: "true"
  CONSUL_HOST: "consul-client"
  CONSUL_PORT: "8500"
  ETL_JOB_IMAGE: ""
  DATAFLOW_ETL_CONTAINER_IMAGE: ""
  DATAFLOW_MAX_WORKERS: "2"
  DATAFLOW_NETWORK: ""
  DATAFLOW_PROJECT_ID: ""
  DATAFLOW_REGION: ""
  DATAFLOW_SERVICE_ACCOUNT: ""
  DATAFLOW_SUB_NETWORK: ""
  DATAFLOW_TEMP_LOCATION: ""
  DATAFLOW_WORKER_SERVICE_ACCOUNT: ""
  EPS_DB_SOURCE: "datastore"
  ES_AUTHENTICATION_ENABLED: "true"
  ES_HOST: ""
  ES_KEYSTORE_PATH: "/elastic-certs/elastic-client-keystore.jks"
  ES_PORT: "9243"
  ES_SSL_ENABLED: "true"
  ES_TRUSTSTORE_PATH: "/elastic-certs/elastic-server-truststore.jks"
  ES_USETRUSTANDKEYSTORE: "false"
  ES_PRIMARY_SHARDS_PER_INDEX: "3"
  ES_REPLICA_SHARDS_PER_INDEX: "2"
  GCP_CRED_PATH: "/gcp_credentials/"
  GCP_PROJECT_ID: ""
  GCP_STORAGE_CREDENTIAL_CONFIG: "/gcp_credentials/gcp-config.yml"
  GOOGLE_GEOCODING_API_KEY: ""
  JAS_AUTH_ENABLED: "false"
  JAS_SIGNATURE_ALGORITHM: "hmac-sha256"
  JAS_SIGNATURE_KEY_ID: "service1-hmac"
  JAS_SIGNATURE_KEY_PATH: "/signature/signaturesecret.txt"
  JAS_TLS_ENABLED: "true"
  JAS_URL: ""
  JWK_RESOURCE_PATH: "/opt/autoid/mounts/jwt/verify-key.json"
  JWT_AUDIENCE: "http://my.service"
  SECRET_ALIAS_ES_KEYSTORE_PASSWORD: ""
  SECRET_ALIAS_ES_KEYSTORE: ""
  SECRET_ALIAS_ES_PASSWORD: ""
  SECRET_ALIAS_ES_TRUSTSTORE_PASSWORD: ""
  SECRET_ALIAS_ES_TRUSTSTORE: ""
  SECRET_ALIAS_ES_USERNAME: ""
  SECRET_ALIAS_JAS_SIGNATURE_KEY: ""
  SECRET_ALIAS_JAS_TLS_KEYSTORE_PASS: ""
  SECRET_ALIAS_JAS_TLS_KEYSTORE: ""
  SECRET_ALIAS_JAS_TLS_TRUSTSTORE_PASS: ""
  SECRET_ALIAS_JAS_TLS_TRUSTSTORE: ""
  TLS_ENABLED: "true"
  TLS_KEYSTORE_KEY_ALIAS: "jasnodekey"
  TLS_KEYSTORE_PATH: "/tls-cert/jas-client-keystore.jks"
  TLS_TRUSTSTORE_PATH: "/tls-cert/jas-server-truststore.jks"
